### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/drupal-actions#2]
## GitHub Actions
- [ ] Module libapache2-mod-php8.1 is not installed (?)
- [ ] apache2 server with php
- [ ] Add a reusable job that will be used from other jobs
- [ ] Cache data inside runner (composer, npm, coverage)
- [ ] Get a live database through ssh

## Drupal project

- [ ] Investigate using https://github.com/phpro/grumphp instead of captainhook. See also https://github.com/search?q=grumphp+drupal
- [ ] Use new core **phpstan** for code validation (https://www.drupal.org/node/3258232)
- [ ] Investigate using [blt](https://github.com/acquia/blt)
